Fix guava classpath conflict by downgrading to 18
Fixes PROJ-123 File upload fails with NoSuchMethodError. 

#comment this was due to a classpath conflict that was not exposed by tests. 
Regression tests added.

#resolve